name: Build and test

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .[dev]
    - name: Analysing the code with pylint
      run: |
        pylint movie_query tests
    - name: Run tests
      run: |
        pytest
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: movie_query:local
